[profile.release]
codegen-units = 1
lto           = true
panic         = "abort"
strip         = true

[workspace]
resolver = "2"
members = [
    "mtas-utils",
    "mtas-cli", 
    "mtas-macro", 
    "mtas-platform", "mtas-core", "mtas-tui", "mtas-gui", 
]

[workspace.dependencies]
tokio = "1.47.1"
