[profile.release]
codegen-units = 1
lto           = true
panic         = "abort"
strip         = true

[workspace]
resolver = "2"
members = [
    "mtas-utils",
    "mtas-cli", 
    "mtas-macro", 
    "mtas-platform", 
]

