[package]
name = "mtas-logger"
version = "0.1.0"
edition = "2024"
license = "MIT"
authors = [ "wenjiu <27843087979@qq.com>" ]

[dependencies]
mtas-macro = { path = "../mtas-macro" }

tracing = { workspace = true }
tracing-subscriber = "0.3"
tracing-appender = "0.2"
anyhow = { workspace = true }
