[package]
name = "mtas-core"
version = "0.1.0"
edition = "2024"
license = "MIT"
authors = [ "wenjiu <27843087979@qq.com>" ]

[dependencies]
mtas-macro = { path = "../mtas-macro" }
mtas-platform = { path = "../mtas-platform" }
tokio = { workspace = true }
adb_client = "2.1.17"
