[package]
name = "mtas-core"
version = "0.1.0"
edition = "2024"
license = "MIT"
authors = [ "wenjiu <27843087979@qq.com>" ]

[dependencies]
mtas-macro = { path = "../mtas-macro" }
mtas-adb = { path = "../mtas-adb" }
anyhow = { workspace = true }
tokio = { workspace = true }
