[package]
name = "mtas-gui"
version = "0.1.0"
edition = "2024"
license = "MIT"
authors = [ "wenjiu <27843087979@qq.com>" ]

[dependencies]
mtas-cli = { path = "../mtas-cli" }
mtas-macro = { path = "../mtas-macro" }
