[package]
name = "mtas-adb"
version = "0.1.0"
edition = "2024"
license = "MIT"
authors = [ "wenjiu <27843087979@qq.com>" ]

[dependencies]
mtas-macro = { path = "../mtas-macro" }
tokio = { workspace = true, features = ["full"] }
adb_client = "2.1.17"
anyhow = { workspace = true }
